//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnoverApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decommissioned
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Reason { get; set; }
    
        public virtual Product Product1 { get; set; }
    }
}
