//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnoverApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Product { get; set; }
        public int Amount { get; set; }
        public string Reauon { get; set; }
    
        public virtual Product Product1 { get; set; }
    }
}
